### ISSUE TITLE
Tokenizerに渡す引数が誤っている

### ISSUE THREAD

**Issue by Piratsuka** [anmonite/expression_trans#1]
## 概要
ローカル環境で実行したところ、正しくトークン化されませんでした。
`self.instance.tokenize(text, 'C') `としたところ、動作したので該当箇所が間違っていると思われます。

## 該当箇所
https://github.com/anmonite/expression_trans/blob/df1d28853766f40b7e7fc621629ec2871b9998d8/expression_trans.py#L272

**Comment by anmonite** [comment]
ご報告ありがとうございます。

開発時に利用していたSudachiPy v0.1.0ではTokenizerのparamは以下の仕様でしたが、その後メソッド関数の引数仕様が変更されたことが原因のようです。

https://github.com/WorksApplications/SudachiPy/blob/v0.1/sudachipy/tokenizer.py

> class Tokenizer:
>     SplitMode = Enum("SplitMode", "A B C")
> 
>     def __init__(self, grammar, lexicon, input_text_plugins, oov_provider_plugins, path_rewrite_plugins):
>         self.grammar = grammar
>         self.lexicon = lexicon
>         self.input_text_plugins = input_text_plugins
>         self.oov_provider_plugins = oov_provider_plugins
>         self.path_rewrite_plugins = path_rewrite_plugins
>         self.dump_output = None
>         self.lattice = lattice.Lattice(grammar)
> 
>         if self.oov_provider_plugins:
>             self.default_oov_provider = self.oov_provider_plugins[-1]
> 
>     def tokenize(self, mode, text):

**Comment by anmonite** [comment]
最新版のSudachiPyでの動作確認をしておりませんので、差し当たってはSudachiPy v1.0をご利用いただくか、全体的な動作保証はできませんがコードを現状に即する形で修正して使っていただくようお願いいたします。

現在フリーランスから正社員になったのもあり、多忙で最新のSudachiPyでの動作検証ができません。
可能であれば、修正して動作検証後に問題なければプルリク飛ばしていただけるとありがたいです(＿ ＿)

**Comment by anmonite** [comment]
最新のSudachiPy v0.5.2で動作するように改修を実施し、v_0,2,1でご指摘の関数仕様変更にも対応しました。
